# Model parameters
model:
  d_model: 512
  n_layers: 6
  n_heads: 8
  ffn_hidden: 2048
  max_seq_length: 256
  dropout: 0.1

# Training parameters
training:
  batch_size: 128
  init_lr: 1e-5
  factor: 0.9
  adam_eps: 5e-9
  patience: 10
  warmup_steps: 100
  epochs: 1000
  clip: 1.0
  weight_decay: 5e-4
  # Additional parameters for RTX 4080 Super optimization
  fp16: true
  gradient_accumulation_steps: 4
  pin_memory: true
  num_workers: 4

# Data parameters
data:
  dataset: "iwslt_en_vi"
  min_freq: 2

# Device settings
device: "cuda" 